spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stayndine_reservations?sslMode=DISABLED&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: stayndine_reservations_app
    password: Mariano!1941
  jpa:
    show-sql: true
  threads:
    virtual:
      enabled: true

security:
  jwt:
    secret: "a1d8b7e0d2b34d3c8f6a9e0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0"

internal:
  api-key: "internal-key"

logging:
  level:
    root: INFO
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

cors:
  allowed-origins:
    - "http://localhost:5173"
    - "http://127.0.0.1:5173"
  allowed-methods: [ GET, POST, PUT, PATCH, DELETE, OPTIONS ]
  allowed-headers: [ Authorization, Content-Type, X-Requested-With ]
  exposed-headers: [ Location ]
  allow-credentials: false

hotels:
  base-url: "http://localhost:8200"
  api-key: "internal-key"