server:
  port: 8300

spring:
  application:
    name: stayndine-reservations
  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: false
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-details: never

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: alpha
    tags-sorter: alpha
